### ISSUE TITLE
Fetched calories are multiplied by 100

### ISSUE THREAD

**Issue by arsenal942** [fitnessforlife/mfp#30]
I've noticed that the daily calorie total is multiplied by 100 unless I've eaten 75,000 calories today. Below is an example of the data returned.

```
{ calories: 74910,
  carbs: 116,
  fat: 12,
  protein: 40,
  cholesterol: 0,
  sodium: 470,
  sugar: 41,
  fiber: 11,
  date: '2017-11-28',
  water: 3 }
```
Easy fix client side (divide by 100) however I thought I'd point it out. I'm using the latest package on npm.

**Comment by andrewzey** [comment]
Want to take a stab at tracking down the issue and fixing this? The site html structure has almost certainly changed, as this definitely wasn't an issue when I first wrote it.

@Aubron do you have bandwidth to take a look?

**Comment by arsenal942** [comment]
@andrewzey I'll have a look over this weekend however no promises due to time constraints. Not a big issue as I'm already doing the division client side however the plugin should fix this eventually.

**Comment by Aubron** [comment]
Yeah I can take a look at this.

**Comment by Aubron** [comment]
@andrewzey - I have a fix ready, but apparently I still don't have the ability to create a new branch on this repository. Is that intentional? I can do the whole song and dance of personal repo, but I figured given the size of the project doing a standard branch->PR flow would work just as well.

**Comment by andrewzey** [comment]
@Aubron Whoops, my mistake. I've updated your permissions, so you should be able to make a branch now.

**Comment by Aubron** [comment]
Essentially the diary printout page has fields for exercise now, so our old jquery selector was grabbing the desired value as well as the exercise totals. For most fields this wasn't an issue as they looked like '81g103', which got parsed out by the tonumber functions, but for unitless values (like calories) it appended through .text() was causing what looked like a multiplication issue.

Fixed with a quick and simple '.first()'
